version: '2'
services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --skip-character-set-client-handshake
    environment:
      - MYSQL_ROOT_PASSWORD=appuser
      - MYSQL_DATABASE=grote
      - MYSQL_USER=grote
      - MYSQL_PASSWORD=appuser
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  app:
    build: .
    working_dir: /grote
    command: bundle exec rails s -b '0.0.0.0'
    environment:
      RAILS_ENV: development
    volumes:
      - .:/grote
    ports:
      - "3000:3000"
    depends_on:
      - db
